name: presensi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0-252.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.19.1
  firebase_auth: 3.4.1
  cloud_firestore: 3.2.1
  firebase_storage: 10.3.1
  group_radio_button: 1.2.0
  flutter_svg: 1.1.1+1
  loader_overlay: 2.0.7
  image_picker: 0.8.5+3
  convex_bottom_bar: 3.0.0
  animated_bottom_navigation_bar: 1.0.1
  intl: 0.17.0
  geolocator: 9.0.1
  geocoding: 2.0.4
  file_picker: ^4.5.1
  pdf: 3.8.2
  path_provider: 2.0.11
  open_file: ^3.2.1
  syncfusion_flutter_datepicker: 20.2.40
  awesome_snackbar_content: 0.0.8
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
    - assets/fonts/Poppins-Regular.ttf

  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 900
  uses-material-design: true

